// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://trvgqfnvoymwgxtlkpvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydmdxZm52b3ltd2d4dGxrcHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDgzMzIsImV4cCI6MjA3MTI4NDMzMn0.WNWvBum1efvaHqYSvFI9R-Nyq_5W39LKCGl6CHzmiRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);